import "../global.css";
export const metadata = {
  title: "Gamified",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-blue500">{children}</body>
    </html>
  );
}
